using System;
using System.Collections.Generic;
using System.Text;

namespace BMSManager
{
    public class BMSConfig
    {
        System.Collections.Hashtable Data;
        string FileName;

        public BMSConfig(string FileName)
        {
            this.FileName = FileName;
            Data = new System.Collections.Hashtable();
        }

        public void Read()
        {
            Data.Clear();

            if (!System.IO.File.Exists(FileName))
                return;

            System.IO.StreamReader r = new System.IO.StreamReader(FileName);
            while(!r.EndOfStream)
            {
                string Line = r.ReadLine();
                int EqPos = Line.IndexOf('=');

                if(EqPos != -1)
                {
                    string Key = Line.Substring(0, EqPos).Trim(),
                        Value = Line.Substring(EqPos+1).Trim();
                    if(Key.Length > 0)
                    {
                        Data.Add(Key, Value);
                    }
                }
            }
            r.Close();
        }

        public void Write()
        {
            System.IO.StreamWriter w = new System.IO.StreamWriter(FileName, false, Encoding.ASCII);
            w.Write("# Generated by b1gMailServer Manager\n");
            w.Write("# " + DateTime.Now.ToString() + "\n");
            foreach(String Key in Data.Keys)
            {
                w.Write(Key + " = " + Data[Key] + "\n");
            }
            w.Close();
        }

        public string Get(string Key)
        {
            if (!Data.ContainsKey(Key))
                return (null);
            return ((string)Data[Key]);
        }

        public void Set(string Key, string Value)
        {
            Data[Key] = Value;
        }
    }  
}
